services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "5050:5050"
    volumes:
      - todo_data:/app/todo.db
    restart: unless-stopped
    environment:
      - TZ=UTC

  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  todo_data:
